### ISSUE TITLE
Bad news, maybe Windows 11 doesn’t have this problem.

### ISSUE THREAD

**Issue by solarflows** [gexgd0419/EdgeWindowTabManagerBlock#1]
When using Edge on Windows 11 to open the same number of tabs on Windows 10, Explorer‘s GDI will not overflow like Windows 10. It seems that Windows 11 has fixed this problem, but Windows 10 has not yet received a patch？

**Comment by solarflows** [comment]
The number of tabs is about 900.

**Comment by gexgd0419** [comment]
A high GDI/user handle count isn't the only problem this program is trying to solve.

Edge can also slow down the Alt-Tab view and the task view (Win+Tab). You can try creating virtual desktops and moving Edge windows between desktops in the task view, while having many tabs open. It can be much slower.

On Windows 11, the task view can be triggered more easily, because now you only need to hover over the task view button. It's not the "full" task view, but it can also be slowed down by Edge.

If even this problem seems to be fixed on your system, I'd like to know your Windows version and Edge version.

**Comment by solarflows** [comment]
> A high GDI/user handle count isn't the only problem this program is trying to solve.
> 
> Edge can also slow down the Alt-Tab view and the task view (Win+Tab). You can try creating virtual desktops and moving Edge windows between desktops in the task view, while having many tabs open. It can be much slower.
> 
> On Windows 11, the task view can be triggered more easily, because now you only need to hover over the task view button. It's not the "full" task view, but it can also be slowed down by Edge.
> 
> If even this problem seems to be fixed on your system, I'd like to know your Windows version and Edge version.

I agree with you, it just not fully stuck Explorer on Windows 11 T.T. What microsoft do in this feature is stupid.
I try amostly every version of Windows 10,even suspected it was a problem with my hardwares, but not luck only Windows 11 is not stuck.
Thank you, create this program.<3
